from PyQt5.QtCore import Qt, QTime, QTimer
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QHBoxLayout, QLabel, QVBoxLayout, QLineEdit
from my_app import *
from instr import *
app = QApplication([])
my_win = QWidget()
my_win.setWindowTitle('Здоровье')
my_win.move(200, 100)
my_win.resize(1000, 600)
class TestWin(QWidget):
    def timer1Event(self):
        global time
        time = QTime(0,0,15)
        self.time = QTimer()
        self,
v_line1 = QVBoxLayout()
v_line2 = QVBoxLayout()
LayoutH1 = QHBoxLayout()
LayoutH2 = QHBoxLayout()
LayoutH3 = QHBoxLayout()
LayoutH4 = QHBoxLayout()
LayoutH5 = QHBoxLayout()
LayoutH6 = QHBoxLayout()
LayoutH7 = QHBoxLayout()
LayoutH8 = QHBoxLayout()
LayoutH9 = QHBoxLayout()
LayoutH10 = QHBoxLayout()
LayoutH11 = QHBoxLayout()
LayoutH12 = QHBoxLayout()
LayoutH13 = QHBoxLayout()
LayoutH14 = QHBoxLayout()

number1 = QLabel('Введите Ф.И.О.:')
lineedit = QLineEdit(txt_hinttest1)
number2 = QLabel('Полных лет:')
lineedit2 = QLineEdit(txt_hinttest2)
number4 = QLabel('Лягте на спину')
button1 = QPushButton('Начать тест')
lineedit3 = QLineEdit(txt_hinttest3)
number5 = QLabel('Приседания')
button2 = QPushButton('Начать делать приседания')
number6 = QLabel('Лягте на спину и пульс')
lineedit4 = QLineEdit()
button3 = QPushButton('Начать финальный тест')
lineedit5 = QLineEdit()
number7 = QPushButton('Отправить результаты')

LayoutH1.addWidget(number1, alignment = Qt.AlignLeft)
LayoutH2.addWidget(lineedit, alignment = Qt.AlignLeft)
LayoutH3.addWidget(number2, alignment = Qt.AlignLeft)
LayoutH4.addWidget(lineedit2, alignment = Qt.AlignLeft)
LayoutH5.addWidget(number4, alignment = Qt.AlignLeft)
LayoutH6.addWidget(button1, alignment = Qt.AlignLeft)
LayoutH7.addWidget(lineedit3, alignment = Qt.AlignLeft)
LayoutH8.addWidget(number5, alignment = Qt.AlignLeft)
LayoutH9.addWidget(button2, alignment = Qt.AlignLeft)
LayoutH10.addWidget(number6, alignment = Qt.AlignLeft)
LayoutH11.addWidget(button3, alignment = Qt.AlignLeft)
LayoutH12.addWidget(lineedit4, alignment = Qt.AlignLeft)
LayoutH13.addWidget(lineedit5, alignment = Qt.AlignLeft)
LayoutH14.addWidget(number7, alignment = Qt.AlignCenter)
v_line1.addLayout(LayoutH1)
v_line1.addLayout(LayoutH2)
v_line1.addLayout(LayoutH3)
v_line1.addLayout(LayoutH4)
v_line1.addLayout(LayoutH5)
v_line1.addLayout(LayoutH6)
v_line1.addLayout(LayoutH7)
v_line1.addLayout(LayoutH8)
v_line1.addLayout(LayoutH9)
v_line1.addLayout(LayoutH10)
v_line1.addLayout(LayoutH11)
v_line1.addLayout(LayoutH12)
v_line1.addLayout(LayoutH13)
v_line1.addLayout(LayoutH14)

my_win.setLayout(v_line1)


my_win.show()
app.exec_()